default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: imperium_development
  username: imperium_user
  password: imperium_user

test:
  <<: *default
  database: imperium_test
  username: imperium_user
  password: imperium_user

production:
  <<: *default
  database: imperium_production
  username: imperium_user
  password: imperium_user
